### ISSUE TITLE
Installation fails on missing README.md (is it included? / is the path correct?)

### ISSUE THREAD

**Issue by bartbroere** [bartbroere/bunqclient#1]
```
Collecting bunqclient
  Downloading https://files.pythonhosted.org/packages/6d/35/ed9daf219fc9c6e8471b10a82d57739520e8dd10f93d64a2036f2497850e/bunqclient-2017.7.17.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-w0c8oc5i/bunqclient/setup.py", line 11, in <module>
        long_description=readme(),
      File "/tmp/pip-build-w0c8oc5i/bunqclient/setup.py", line 4, in readme
        with open('README.md') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-w0c8oc5i/bunqclient/
```

**Comment by kazoni** [comment]
Which version of Python are you running this on?  I was able to run it without issue on 2.7.18rc1

`running egg_info`
`creating bunqclient.egg-info`  
`writing requirements to bunqclient.egg-info/requires.txt`
`writing bunqclient.egg-info/PKG-INFO`
`writing top-level names to bunqclient.egg-info/top_level.txt`
`writing dependency_links to bunqclient.egg-info/dependency_links.txt`
`writing manifest file 'bunqclient.egg-info/SOURCES.txt'`
`reading manifest file 'bunqclient.egg-info/SOURCES.txt'`
`writing manifest file 'bunqclient.egg-info/SOURCES.txt'`
